# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Use official lightweight Node.js image
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

# Install and build
RUN npm ci && npm run build

# Default command to run the MCP server
CMD ["node", "build/index.js"]
